// 英語動詞クイズ 問題データ
// 各問: { id, cat, sub, jp, subject(固定表示の主語), answer(答え=動詞句), alts(許容表記), tail(後続文), full, note }
// 答えは「動詞・動詞句」。主語と後続文は固定表示し、間の動詞句を答える。
// 難しすぎる表現は避け、日常会話〜簡単なビジネスをカバー。

const QUESTIONS = [
  // ===== 日常: 移動・交通 (daily / commute) =====
  { id: "c001", cat: "daily", sub: "移動", jp: "駅まで走った", subject: "I", answer: "ran", tail: "to the station.", full: "I ran to the station.", note: "走った = ran（runの過去形）。" },
  { id: "c002", cat: "daily", sub: "移動", jp: "いつも乗る電車に乗り遅れた", subject: "I", answer: "missed", tail: "the train I usually take.", full: "I missed the train I usually take.", note: "乗り遅れた = missed。" },
  { id: "c003", cat: "daily", sub: "移動", jp: "次の電車を待った", subject: "I", answer: "waited", tail: "for the next train.", full: "I waited for the next train.", note: "待つ = wait for。" },
  { id: "c004", cat: "daily", sub: "移動", jp: "反対方向の電車に乗ってしまった", subject: "I", answer: "took", tail: "the train in the wrong direction.", full: "I took the train in the wrong direction.", note: "電車に乗った = took the train。" },
  { id: "c005", cat: "daily", sub: "移動", jp: "乗り換えを間違えた", subject: "I", answer: "made", tail: "the wrong transfer.", alts: ["took"], full: "I made the wrong transfer.", note: "間違えた = made a mistake / took the wrong ...。" },
  { id: "c006", cat: "daily", sub: "移動", jp: "道に迷った", subject: "I", answer: "got", tail: "lost.", full: "I got lost.", note: "迷った = got lost。" },
  { id: "c007", cat: "daily", sub: "移動", jp: "バス停を通り過ぎてしまった", subject: "I", answer: "missed", tail: "my bus stop.", full: "I missed my bus stop.", note: "降りる場所を逃した = missed。" },
  { id: "c008", cat: "daily", sub: "移動", jp: "タクシーを呼んだ", subject: "I", answer: "called", tail: "a taxi.", full: "I called a taxi.", note: "呼んだ = called。" },
  { id: "c009", cat: "daily", sub: "移動", jp: "始発電車に間に合った", subject: "I", answer: "caught", tail: "the first train.", full: "I caught the first train.", note: "間に合って乗った = caught。" },
  { id: "c010", cat: "daily", sub: "移動", jp: "歩いて家に帰った", subject: "I", answer: "walked", tail: "home.", full: "I walked home.", note: "歩いて帰った = walked home（homeに前置詞は不要）。" },
  { id: "c011", cat: "daily", sub: "移動", jp: "自転車で職場に行った", subject: "I", answer: "rode", tail: "my bike to work.", full: "I rode my bike to work.", note: "自転車に乗って = rode my bike。" },
  { id: "c012", cat: "daily", sub: "移動", jp: "予定より早く着いた", subject: "I", answer: "arrived", tail: "early.", full: "I arrived early.", note: "早く着いた = arrived early。" },
  { id: "c013", cat: "daily", sub: "移動", jp: "5分遅れて着いた", subject: "I", answer: "arrived", tail: "five minutes late.", full: "I arrived five minutes late.", note: "遅れて着いた = arrived ... late。" },
  { id: "c014", cat: "daily", sub: "移動", jp: "終電を逃した", subject: "I", answer: "missed", tail: "the last train.", full: "I missed the last train.", note: "終電 = the last train。" },
  { id: "c015", cat: "daily", sub: "移動", jp: "次の駅で降りた", subject: "I", answer: "got", tail: "off at the next station.", full: "I got off at the next station.", note: "降りた = got off。" },
  { id: "c016", cat: "daily", sub: "移動", jp: "電車に乗った", subject: "I", answer: "got", tail: "on the train.", full: "I got on the train.", note: "乗り込んだ = got on。" },
  { id: "c017", cat: "daily", sub: "移動", jp: "駅で友だちと待ち合わせた", subject: "I", answer: "met", tail: "my friend at the station.", full: "I met my friend at the station.", note: "会った = met。" },
  { id: "c018", cat: "daily", sub: "移動", jp: "車を駐車場に停めた", subject: "I", answer: "parked", tail: "my car in the parking lot.", full: "I parked my car in the parking lot.", note: "停めた = parked。" },
  { id: "c019", cat: "daily", sub: "移動", jp: "ガソリンを入れた", subject: "I", answer: "got", tail: "some gas.", alts: ["filled up"], full: "I got some gas.", note: "給油した = got gas / filled up。" },
  { id: "c020", cat: "daily", sub: "移動", jp: "渋滞にはまった", subject: "I", answer: "got", tail: "stuck in traffic.", full: "I got stuck in traffic.", note: "渋滞にはまった = got stuck in traffic。" },

  // ===== 日常: 買い物 (daily / shopping) =====
  { id: "s001", cat: "daily", sub: "買い物", jp: "薬局で薬を買った", subject: "I", answer: "bought", tail: "some medicine at the pharmacy.", full: "I bought some medicine at the pharmacy.", note: "買った = bought。" },
  { id: "s002", cat: "daily", sub: "買い物", jp: "レジで支払いを済ませた", subject: "I", answer: "paid", tail: "at the register.", full: "I paid at the register.", note: "支払った = paid。" },
  { id: "s003", cat: "daily", sub: "買い物", jp: "レシートを捨ててしまった", subject: "I", answer: "threw", tail: "away the receipt.", full: "I threw away the receipt.", note: "捨てた = threw away。" },
  { id: "s004", cat: "daily", sub: "買い物", jp: "間違ったものを注文した", subject: "I", answer: "ordered", tail: "the wrong item.", full: "I ordered the wrong item.", note: "注文した = ordered。" },
  { id: "s005", cat: "daily", sub: "買い物", jp: "店員に在庫を聞いた", subject: "I", answer: "asked", tail: "the staff if they had it in stock.", full: "I asked the staff if they had it in stock.", note: "聞いた = asked。" },
  { id: "s006", cat: "daily", sub: "買い物", jp: "セールで安く買えた", subject: "I", answer: "got", tail: "it cheap on sale.", full: "I got it cheap on sale.", note: "手に入れた = got。" },
  { id: "s007", cat: "daily", sub: "買い物", jp: "エコバッグを持ってくるのを忘れた", subject: "I", answer: "forgot", tail: "to bring my eco bag.", full: "I forgot to bring my eco bag.", note: "〜し忘れた = forgot to。" },
  { id: "s008", cat: "daily", sub: "買い物", jp: "クレジットカードで払った", subject: "I", answer: "paid", tail: "by credit card.", full: "I paid by credit card.", note: "カードで = paid by credit card。" },
  { id: "s009", cat: "daily", sub: "買い物", jp: "値段を比べた", subject: "I", answer: "compared", tail: "the prices.", full: "I compared the prices.", note: "比べた = compared。" },
  { id: "s010", cat: "daily", sub: "買い物", jp: "返品した", subject: "I", answer: "returned", tail: "the item.", full: "I returned the item.", note: "返品した = returned。" },
  { id: "s011", cat: "daily", sub: "買い物", jp: "ポイントをためた", subject: "I", answer: "earned", tail: "some points.", full: "I earned some points.", note: "ためた = earned。" },
  { id: "s012", cat: "daily", sub: "買い物", jp: "買い物リストを作った", subject: "I", answer: "made", tail: "a shopping list.", full: "I made a shopping list.", note: "作った = made。" },
  { id: "s013", cat: "daily", sub: "買い物", jp: "牛乳を買い忘れた", subject: "I", answer: "forgot", tail: "to buy milk.", full: "I forgot to buy milk.", note: "買い忘れた = forgot to buy。" },
  { id: "s014", cat: "daily", sub: "買い物", jp: "おつりをもらった", subject: "I", answer: "got", tail: "my change.", full: "I got my change.", note: "おつり = change。" },
  { id: "s015", cat: "daily", sub: "買い物", jp: "試着した", subject: "I", answer: "tried", tail: "it on.", full: "I tried it on.", note: "試着した = tried it on。" },

  // ===== 日常: 予約・手続き (daily / booking) =====
  { id: "k001", cat: "daily", sub: "予約", jp: "予約を変更した", subject: "I", answer: "changed", tail: "my reservation.", full: "I changed my reservation.", note: "変更した = changed。" },
  { id: "k002", cat: "daily", sub: "予約", jp: "予約をキャンセルした", subject: "I", answer: "canceled", alts: ["cancelled"], tail: "my reservation.", full: "I canceled my reservation.", note: "キャンセルした = canceled / cancelled。" },
  { id: "k003", cat: "daily", sub: "予約", jp: "予約を取り直した", subject: "I", answer: "rebooked", tail: "my appointment.", full: "I rebooked my appointment.", note: "取り直した = rebooked。" },
  { id: "k004", cat: "daily", sub: "予約", jp: "オンラインで予約した", subject: "I", answer: "booked", tail: "it online.", full: "I booked it online.", note: "予約した = booked。" },
  { id: "k005", cat: "daily", sub: "予約", jp: "予約の30分前に着いた", subject: "I", answer: "arrived", tail: "30 minutes before my appointment.", full: "I arrived 30 minutes before my appointment.", note: "着いた = arrived。" },
  { id: "k006", cat: "daily", sub: "予約", jp: "予約を確認した", subject: "I", answer: "confirmed", tail: "my reservation.", full: "I confirmed my reservation.", note: "確認・確定した = confirmed。" },
  { id: "k007", cat: "daily", sub: "予約", jp: "窓口で手続きをした", subject: "I", answer: "filled", tail: "out the form at the counter.", full: "I filled out the form at the counter.", note: "記入した = filled out。" },
  { id: "k008", cat: "daily", sub: "予約", jp: "順番を待った", subject: "I", answer: "waited", tail: "for my turn.", full: "I waited for my turn.", note: "順番を待った = waited for my turn。" },
  { id: "k009", cat: "daily", sub: "予約", jp: "整理券を取った", subject: "I", answer: "took", tail: "a numbered ticket.", full: "I took a numbered ticket.", note: "取った = took。" },
  { id: "k010", cat: "daily", sub: "予約", jp: "病院に電話して予約を取った", subject: "I", answer: "called", tail: "the clinic to make an appointment.", full: "I called the clinic to make an appointment.", note: "電話した = called。" },
  { id: "k011", cat: "daily", sub: "予約", jp: "美容院を予約した", subject: "I", answer: "made", tail: "an appointment at the salon.", full: "I made an appointment at the salon.", note: "予約した = made an appointment。" },
  { id: "k012", cat: "daily", sub: "予約", jp: "レストランの席を予約した", subject: "I", answer: "reserved", tail: "a table at the restaurant.", full: "I reserved a table at the restaurant.", note: "席を予約した = reserved a table。" },

  // ===== 日常: 体調 (daily / health) =====
  { id: "h001", cat: "daily", sub: "体調", jp: "少し頭が痛かった", subject: "I", answer: "had", tail: "a slight headache.", full: "I had a slight headache.", note: "痛みがあった = had。" },
  { id: "h002", cat: "daily", sub: "体調", jp: "のどが痛かった", subject: "I", answer: "had", tail: "a sore throat.", full: "I had a sore throat.", note: "のどが痛い = have a sore throat。" },
  { id: "h003", cat: "daily", sub: "体調", jp: "薬を飲んだ", subject: "I", answer: "took", tail: "some medicine.", full: "I took some medicine.", note: "薬を飲む = take medicine。" },
  { id: "h004", cat: "daily", sub: "体調", jp: "熱を測った", subject: "I", answer: "took", tail: "my temperature.", full: "I took my temperature.", note: "熱を測る = take one's temperature。" },
  { id: "h005", cat: "daily", sub: "体調", jp: "少し熱があった", subject: "I", answer: "had", tail: "a slight fever.", full: "I had a slight fever.", note: "熱があった = had a fever。" },
  { id: "h006", cat: "daily", sub: "体調", jp: "早めに寝た", subject: "I", answer: "went", tail: "to bed early.", full: "I went to bed early.", note: "寝た = went to bed。" },
  { id: "h007", cat: "daily", sub: "体調", jp: "ぐっすり眠れた", subject: "I", answer: "slept", tail: "well.", full: "I slept well.", note: "よく眠れた = slept well。" },
  { id: "h008", cat: "daily", sub: "体調", jp: "あまり眠れなかった", subject: "I", answer: "didn't", alts: ["did not"], tail: "sleep well.", full: "I didn't sleep well.", note: "眠れなかった = didn't sleep well。" },
  { id: "h009", cat: "daily", sub: "体調", jp: "風邪をひいた", subject: "I", answer: "caught", tail: "a cold.", full: "I caught a cold.", note: "風邪をひいた = caught a cold。" },
  { id: "h010", cat: "daily", sub: "体調", jp: "病院に行った", subject: "I", answer: "went", tail: "to the doctor.", full: "I went to the doctor.", note: "病院（医者）に行った = went to the doctor。" },
  { id: "h011", cat: "daily", sub: "体調", jp: "少し休んだ", subject: "I", answer: "took", tail: "a short rest.", full: "I took a short rest.", note: "休んだ = took a rest。" },
  { id: "h012", cat: "daily", sub: "体調", jp: "気分が良くなった", subject: "I", answer: "felt", tail: "better.", full: "I felt better.", note: "良くなった = felt better。" },
  { id: "h013", cat: "daily", sub: "体調", jp: "ストレッチをした", subject: "I", answer: "did", tail: "some stretches.", full: "I did some stretches.", note: "ストレッチをした = did some stretches。" },
  { id: "h014", cat: "daily", sub: "体調", jp: "水をたくさん飲んだ", subject: "I", answer: "drank", tail: "a lot of water.", full: "I drank a lot of water.", note: "飲んだ = drank。" },
  { id: "h015", cat: "daily", sub: "体調", jp: "マスクをつけた", subject: "I", answer: "put", tail: "on a mask.", full: "I put on a mask.", note: "つけた = put on。" },

  // ===== 日常: 家事 (daily / chores) =====
  { id: "ch01", cat: "daily", sub: "家事", jp: "洗濯機を回した", subject: "I", answer: "did", tail: "the laundry.", alts: ["started"], full: "I did the laundry.", note: "洗濯した = did the laundry。" },
  { id: "ch02", cat: "daily", sub: "家事", jp: "皿を洗った", subject: "I", answer: "washed", tail: "the dishes.", full: "I washed the dishes.", note: "洗った = washed。" },
  { id: "ch03", cat: "daily", sub: "家事", jp: "部屋を掃除した", subject: "I", answer: "cleaned", tail: "my room.", full: "I cleaned my room.", note: "掃除した = cleaned。" },
  { id: "ch04", cat: "daily", sub: "家事", jp: "ゴミを出した", subject: "I", answer: "took", tail: "out the trash.", full: "I took out the trash.", note: "ゴミを出した = took out the trash。" },
  { id: "ch05", cat: "daily", sub: "家事", jp: "床に掃除機をかけた", subject: "I", answer: "vacuumed", tail: "the floor.", full: "I vacuumed the floor.", note: "掃除機をかけた = vacuumed。" },
  { id: "ch06", cat: "daily", sub: "家事", jp: "ベッドを整えた", subject: "I", answer: "made", tail: "the bed.", full: "I made the bed.", note: "ベッドを整える = make the bed。" },
  { id: "ch07", cat: "daily", sub: "家事", jp: "洗濯物をたたんだ", subject: "I", answer: "folded", tail: "the laundry.", full: "I folded the laundry.", note: "たたんだ = folded。" },
  { id: "ch08", cat: "daily", sub: "家事", jp: "夕食を作った", subject: "I", answer: "cooked", tail: "dinner.", alts: ["made"], full: "I cooked dinner.", note: "作った = cooked / made。" },
  { id: "ch09", cat: "daily", sub: "家事", jp: "テーブルを片づけた", subject: "I", answer: "cleared", tail: "the table.", full: "I cleared the table.", note: "片づけた = cleared。" },
  { id: "ch10", cat: "daily", sub: "家事", jp: "植物に水をやった", subject: "I", answer: "watered", tail: "the plants.", full: "I watered the plants.", note: "水をやった = watered。" },
  { id: "ch11", cat: "daily", sub: "家事", jp: "電気を消した", subject: "I", answer: "turned", tail: "off the lights.", full: "I turned off the lights.", note: "消した = turned off。" },
  { id: "ch12", cat: "daily", sub: "家事", jp: "エアコンをつけた", subject: "I", answer: "turned", tail: "on the air conditioner.", full: "I turned on the air conditioner.", note: "つけた = turned on。" },
  { id: "ch13", cat: "daily", sub: "家事", jp: "買い置きが切れていた", subject: "I", answer: "ran", tail: "out of supplies.", full: "I ran out of supplies.", note: "切れた = ran out of。" },
  { id: "ch14", cat: "daily", sub: "家事", jp: "冷蔵庫を整理した", subject: "I", answer: "organized", tail: "the fridge.", full: "I organized the fridge.", note: "整理した = organized。" },

  // ===== 日常: 飲食 (daily / food) =====
  { id: "f001", cat: "daily", sub: "飲食", jp: "急いで朝ごはんを食べた", subject: "I", answer: "had", tail: "breakfast in a hurry.", full: "I had breakfast in a hurry.", note: "食事をした = had。" },
  { id: "f002", cat: "daily", sub: "飲食", jp: "昼食を抜いた", subject: "I", answer: "skipped", tail: "lunch.", full: "I skipped lunch.", note: "抜いた = skipped。" },
  { id: "f003", cat: "daily", sub: "飲食", jp: "コーヒーを淹れた", subject: "I", answer: "made", tail: "some coffee.", full: "I made some coffee.", note: "淹れた = made。" },
  { id: "f004", cat: "daily", sub: "飲食", jp: "外食した", subject: "I", answer: "ate", tail: "out.", full: "I ate out.", note: "外食した = ate out。" },
  { id: "f005", cat: "daily", sub: "飲食", jp: "料理を温め直した", subject: "I", answer: "reheated", tail: "the food.", full: "I reheated the food.", note: "温め直した = reheated。" },
  { id: "f006", cat: "daily", sub: "飲食", jp: "テイクアウトを頼んだ", subject: "I", answer: "ordered", tail: "takeout.", full: "I ordered takeout.", note: "頼んだ = ordered。" },
  { id: "f007", cat: "daily", sub: "飲食", jp: "おやつを少し食べた", subject: "I", answer: "had", tail: "a small snack.", full: "I had a small snack.", note: "食べた = had。" },
  { id: "f008", cat: "daily", sub: "飲食", jp: "デザートを分け合った", subject: "I", answer: "shared", tail: "a dessert.", full: "I shared a dessert.", note: "分け合った = shared。" },
  { id: "f009", cat: "daily", sub: "飲食", jp: "お弁当を作った", subject: "I", answer: "made", tail: "a lunch box.", full: "I made a lunch box.", note: "作った = made。" },
  { id: "f010", cat: "daily", sub: "飲食", jp: "水を一杯飲んだ", subject: "I", answer: "drank", tail: "a glass of water.", full: "I drank a glass of water.", note: "飲んだ = drank。" },
  { id: "f011", cat: "daily", sub: "飲食", jp: "食べ過ぎた", subject: "I", answer: "ate", tail: "too much.", full: "I ate too much.", note: "食べ過ぎた = ate too much。" },
  { id: "f012", cat: "daily", sub: "飲食", jp: "夕食をごちそうした", subject: "I", answer: "treated", tail: "my friend to dinner.", full: "I treated my friend to dinner.", note: "ごちそうした = treated。" },

  // ===== 日常: 連絡・予定 (daily / contact) =====
  { id: "n001", cat: "daily", sub: "連絡", jp: "友だちにメッセージを送った", subject: "I", answer: "sent", tail: "a message to my friend.", full: "I sent a message to my friend.", note: "送った = sent。" },
  { id: "n002", cat: "daily", sub: "連絡", jp: "返信するのを忘れた", subject: "I", answer: "forgot", tail: "to reply.", full: "I forgot to reply.", note: "返信し忘れた = forgot to reply。" },
  { id: "n003", cat: "daily", sub: "連絡", jp: "電話をかけ直した", subject: "I", answer: "called", tail: "back.", full: "I called back.", note: "かけ直した = called back。" },
  { id: "n004", cat: "daily", sub: "連絡", jp: "予定を確認した", subject: "I", answer: "checked", tail: "my schedule.", full: "I checked my schedule.", note: "確認した = checked。" },
  { id: "n005", cat: "daily", sub: "連絡", jp: "予定を空けた", subject: "I", answer: "cleared", tail: "my schedule.", full: "I cleared my schedule.", note: "空けた = cleared。" },
  { id: "n006", cat: "daily", sub: "連絡", jp: "約束の時間を決めた", subject: "I", answer: "set", tail: "a time to meet.", full: "I set a time to meet.", note: "決めた = set。" },
  { id: "n007", cat: "daily", sub: "連絡", jp: "写真を送った", subject: "I", answer: "sent", tail: "the photo.", full: "I sent the photo.", note: "送った = sent。" },
  { id: "n008", cat: "daily", sub: "連絡", jp: "電話に出られなかった", subject: "I", answer: "missed", tail: "the call.", full: "I missed the call.", note: "出られなかった = missed the call。" },
  { id: "n009", cat: "daily", sub: "連絡", jp: "後で電話すると伝えた", subject: "I", answer: "said", tail: "I would call later.", full: "I said I would call later.", note: "伝えた = said。" },
  { id: "n010", cat: "daily", sub: "連絡", jp: "予定を立てた", subject: "I", answer: "made", tail: "plans.", full: "I made plans.", note: "予定を立てた = made plans。" },
  { id: "n011", cat: "daily", sub: "連絡", jp: "待ち合わせ場所を変えた", subject: "I", answer: "changed", tail: "the meeting place.", full: "I changed the meeting place.", note: "変えた = changed。" },
  { id: "n012", cat: "daily", sub: "連絡", jp: "遅れると連絡した", subject: "I", answer: "texted", tail: "that I would be late.", full: "I texted that I would be late.", note: "（メッセージで）連絡した = texted。" },

  // ===== 日常: 天気・外出 (daily / weather) =====
  { id: "w001", cat: "daily", sub: "天気", jp: "家を出る前に天気を確認した", subject: "I", answer: "checked", tail: "the weather before leaving home.", full: "I checked the weather before leaving home.", note: "確認した = checked。" },
  { id: "w002", cat: "daily", sub: "天気", jp: "傘を持って行った", subject: "I", answer: "took", tail: "an umbrella with me.", full: "I took an umbrella with me.", note: "持って行った = took。" },
  { id: "w003", cat: "daily", sub: "天気", jp: "傘を持って行くのを忘れた", subject: "I", answer: "forgot", tail: "to take an umbrella.", full: "I forgot to take an umbrella.", note: "忘れた = forgot to。" },
  { id: "w004", cat: "daily", sub: "天気", jp: "雨がやんだので外に出た", subject: "I", answer: "went", tail: "out after the rain stopped.", full: "I went out after the rain stopped.", note: "外に出た = went out。" },
  { id: "w005", cat: "daily", sub: "天気", jp: "上着を一枚はおった", subject: "I", answer: "put", tail: "on a jacket.", full: "I put on a jacket.", note: "はおった = put on。" },
  { id: "w006", cat: "daily", sub: "天気", jp: "暑かったので上着を脱いだ", subject: "I", answer: "took", tail: "off my jacket because it was hot.", full: "I took off my jacket because it was hot.", note: "脱いだ = took off。" },
  { id: "w007", cat: "daily", sub: "天気", jp: "日焼け止めを塗った", subject: "I", answer: "put", tail: "on sunscreen.", full: "I put on sunscreen.", note: "塗った = put on。" },
  { id: "w008", cat: "daily", sub: "天気", jp: "窓を開けた", subject: "I", answer: "opened", tail: "the window.", full: "I opened the window.", note: "開けた = opened。" },
  { id: "w009", cat: "daily", sub: "天気", jp: "洗濯物を取り込んだ", subject: "I", answer: "brought", tail: "in the laundry.", full: "I brought in the laundry.", note: "取り込んだ = brought in。" },
  { id: "w010", cat: "daily", sub: "天気", jp: "散歩に出かけた", subject: "I", answer: "went", tail: "for a walk.", full: "I went for a walk.", note: "散歩に行った = went for a walk。" },

  // ===== 日常: 家族・人 (daily / family) =====
  { id: "fa01", cat: "daily", sub: "家族", jp: "子どもを学校に送った", subject: "I", answer: "took", tail: "my child to school.", full: "I took my child to school.", note: "送って行った = took ... to。" },
  { id: "fa02", cat: "daily", sub: "家族", jp: "子どもを迎えに行った", subject: "I", answer: "picked", tail: "up my child.", full: "I picked up my child.", note: "迎えに行った = picked up。" },
  { id: "fa03", cat: "daily", sub: "家族", jp: "母に電話した", subject: "I", answer: "called", tail: "my mother.", full: "I called my mother.", note: "電話した = called。" },
  { id: "fa04", cat: "daily", sub: "家族", jp: "宿題を手伝った", subject: "I", answer: "helped", tail: "with the homework.", full: "I helped with the homework.", note: "手伝った = helped with。" },
  { id: "fa05", cat: "daily", sub: "家族", jp: "家族と夕食を食べた", subject: "I", answer: "had", tail: "dinner with my family.", full: "I had dinner with my family.", note: "食べた = had。" },
  { id: "fa06", cat: "daily", sub: "家族", jp: "友だちを家に招いた", subject: "I", answer: "invited", tail: "a friend over.", full: "I invited a friend over.", note: "招いた = invited ... over。" },
  { id: "fa07", cat: "daily", sub: "家族", jp: "誕生日を祝った", subject: "I", answer: "celebrated", tail: "her birthday.", full: "I celebrated her birthday.", note: "祝った = celebrated。" },
  { id: "fa08", cat: "daily", sub: "家族", jp: "プレゼントを買った", subject: "I", answer: "bought", tail: "a present.", full: "I bought a present.", note: "買った = bought。" },
  { id: "fa09", cat: "daily", sub: "家族", jp: "犬を散歩させた", subject: "I", answer: "walked", tail: "the dog.", full: "I walked the dog.", note: "散歩させた = walked。" },
  { id: "fa10", cat: "daily", sub: "家族", jp: "祖父母に会いに行った", subject: "I", answer: "visited", tail: "my grandparents.", full: "I visited my grandparents.", note: "会いに行った = visited。" },

  // ===== 日常: 余暇 (daily / leisure) =====
  { id: "l001", cat: "daily", sub: "余暇", jp: "少し休んだ", subject: "I", answer: "took", tail: "a short break.", full: "I took a short break.", note: "休憩した = took a break。" },
  { id: "l002", cat: "daily", sub: "余暇", jp: "昼寝をした", subject: "I", answer: "took", tail: "a nap.", full: "I took a nap.", note: "昼寝した = took a nap。" },
  { id: "l003", cat: "daily", sub: "余暇", jp: "カフェで時間をつぶした", subject: "I", answer: "killed", tail: "some time at a cafe.", full: "I killed some time at a cafe.", note: "時間をつぶす = kill time。" },
  { id: "l004", cat: "daily", sub: "余暇", jp: "映画を見た", subject: "I", answer: "watched", tail: "a movie.", full: "I watched a movie.", note: "見た = watched。" },
  { id: "l005", cat: "daily", sub: "余暇", jp: "本を少し読んだ", subject: "I", answer: "read", tail: "a few pages.", full: "I read a few pages.", note: "読んだ = read（過去形も同じ綴り）。" },
  { id: "l006", cat: "daily", sub: "余暇", jp: "音楽を聴いた", subject: "I", answer: "listened", tail: "to some music.", full: "I listened to some music.", note: "聴いた = listened to。" },
  { id: "l007", cat: "daily", sub: "余暇", jp: "ジムで運動した", subject: "I", answer: "worked", tail: "out at the gym.", full: "I worked out at the gym.", note: "運動した = worked out。" },
  { id: "l008", cat: "daily", sub: "余暇", jp: "ゲームを少しした", subject: "I", answer: "played", tail: "a video game for a while.", full: "I played a video game for a while.", note: "した = played。" },
  { id: "l009", cat: "daily", sub: "余暇", jp: "写真を撮った", subject: "I", answer: "took", tail: "a photo.", full: "I took a photo.", note: "写真を撮る = take a photo。" },
  { id: "l010", cat: "daily", sub: "余暇", jp: "新しい趣味を始めた", subject: "I", answer: "started", tail: "a new hobby.", full: "I started a new hobby.", note: "始めた = started。" },
  { id: "l011", cat: "daily", sub: "余暇", jp: "公園でリラックスした", subject: "I", answer: "relaxed", tail: "in the park.", full: "I relaxed in the park.", note: "リラックスした = relaxed。" },
  { id: "l012", cat: "daily", sub: "余暇", jp: "友だちと出かけた", subject: "I", answer: "hung", tail: "out with my friends.", full: "I hung out with my friends.", note: "出かけて遊んだ = hung out。" },

  // ===== 日常: 失敗・トラブル (daily / trouble) =====
  { id: "t001", cat: "daily", sub: "トラブル", jp: "鍵を家に忘れた", subject: "I", answer: "left", tail: "my keys at home.", full: "I left my keys at home.", note: "置き忘れた = left。" },
  { id: "t002", cat: "daily", sub: "トラブル", jp: "財布を持ってくるのを忘れた", subject: "I", answer: "forgot", tail: "to bring my wallet.", full: "I forgot to bring my wallet.", note: "忘れた = forgot to。" },
  { id: "t003", cat: "daily", sub: "トラブル", jp: "スマホを落とした", subject: "I", answer: "dropped", tail: "my phone.", full: "I dropped my phone.", note: "落とした = dropped。" },
  { id: "t004", cat: "daily", sub: "トラブル", jp: "コーヒーをこぼした", subject: "I", answer: "spilled", tail: "my coffee.", full: "I spilled my coffee.", note: "こぼした = spilled。" },
  { id: "t005", cat: "daily", sub: "トラブル", jp: "傘を電車に忘れた", subject: "I", answer: "left", tail: "my umbrella on the train.", full: "I left my umbrella on the train.", note: "忘れた = left。" },
  { id: "t006", cat: "daily", sub: "トラブル", jp: "予定をすっかり忘れていた", subject: "I", answer: "completely", tail: "forgot about it.", alts: ["forgot"], full: "I completely forgot about it.", note: "すっかり忘れた = completely forgot。" },
  { id: "t007", cat: "daily", sub: "トラブル", jp: "道で転んだ", subject: "I", answer: "fell", tail: "down on the street.", full: "I fell down on the street.", note: "転んだ = fell down。" },
  { id: "t008", cat: "daily", sub: "トラブル", jp: "パスワードを忘れた", subject: "I", answer: "forgot", tail: "my password.", full: "I forgot my password.", note: "忘れた = forgot。" },
  { id: "t009", cat: "daily", sub: "トラブル", jp: "充電器を持ってくるのを忘れた", subject: "I", answer: "forgot", tail: "to bring my charger.", full: "I forgot to bring my charger.", note: "忘れた = forgot to。" },
  { id: "t010", cat: "daily", sub: "トラブル", jp: "電車を間違えた", subject: "I", answer: "got", tail: "on the wrong train.", full: "I got on the wrong train.", note: "間違えて乗った = got on the wrong train。" },

  // ===== ビジネス: メール・連絡 (business / email) =====
  { id: "be01", cat: "business", sub: "メール", jp: "資料を送りました", subject: "I", answer: "sent", tail: "the document.", full: "I sent the document.", note: "送った = sent。" },
  { id: "be02", cat: "business", sub: "メール", jp: "メールを確認しました", subject: "I", answer: "checked", tail: "the email.", full: "I checked the email.", note: "確認した = checked。" },
  { id: "be03", cat: "business", sub: "メール", jp: "添付ファイルを確認しました", subject: "I", answer: "checked", tail: "the attachment.", full: "I checked the attachment.", note: "確認した = checked。" },
  { id: "be04", cat: "business", sub: "メール", jp: "メールを転送しました", subject: "I", answer: "forwarded", tail: "the email.", full: "I forwarded the email.", note: "転送した = forwarded。" },
  { id: "be05", cat: "business", sub: "メール", jp: "全員に返信しました", subject: "I", answer: "replied", tail: "to everyone.", full: "I replied to everyone.", note: "返信した = replied。" },
  { id: "be06", cat: "business", sub: "メール", jp: "ファイルを添付しました", subject: "I", answer: "attached", tail: "the file.", full: "I attached the file.", note: "添付した = attached。" },
  { id: "be07", cat: "business", sub: "メール", jp: "CCに上司を入れました", subject: "I", answer: "added", tail: "my manager in CC.", full: "I added my manager in CC.", note: "入れた = added。" },
  { id: "be08", cat: "business", sub: "メール", jp: "あとで返信します", subject: "I", answer: "will", tail: "reply later.", full: "I will reply later.", note: "これからやる = will reply。" },
  { id: "be09", cat: "business", sub: "メール", jp: "午前中に返信します", subject: "I", answer: "will", tail: "reply in the morning.", full: "I will reply in the morning.", note: "返信します = will reply。" },
  { id: "be10", cat: "business", sub: "メール", jp: "明日までに送ります", subject: "I", answer: "will", tail: "send it by tomorrow.", full: "I will send it by tomorrow.", note: "送ります = will send。" },
  { id: "be11", cat: "business", sub: "メール", jp: "リンクを共有しました", subject: "I", answer: "shared", tail: "the link.", full: "I shared the link.", note: "共有した = shared。" },
  { id: "be12", cat: "business", sub: "メール", jp: "受け取りました", subject: "I", answer: "received", tail: "it.", full: "I received it.", note: "受け取った = received。" },

  // ===== ビジネス: 会議 (business / meeting) =====
  { id: "bm01", cat: "business", sub: "会議", jp: "会議を設定しました", subject: "I", answer: "set", tail: "up the meeting.", full: "I set up the meeting.", note: "設定した = set up。" },
  { id: "bm02", cat: "business", sub: "会議", jp: "会議を延期しました", subject: "I", answer: "postponed", tail: "the meeting.", full: "I postponed the meeting.", note: "延期した = postponed。" },
  { id: "bm03", cat: "business", sub: "会議", jp: "会議をキャンセルしました", subject: "I", answer: "canceled", alts: ["cancelled"], tail: "the meeting.", full: "I canceled the meeting.", note: "キャンセルした = canceled。" },
  { id: "bm04", cat: "business", sub: "会議", jp: "会議に参加しました", subject: "I", answer: "joined", tail: "the meeting.", full: "I joined the meeting.", note: "参加した = joined。" },
  { id: "bm05", cat: "business", sub: "会議", jp: "会議を抜けました", subject: "I", answer: "left", tail: "the meeting.", full: "I left the meeting.", note: "退出した = left。" },
  { id: "bm06", cat: "business", sub: "会議", jp: "議事録を取りました", subject: "I", answer: "took", tail: "notes during the meeting.", full: "I took notes during the meeting.", note: "メモを取った = took notes。" },
  { id: "bm07", cat: "business", sub: "会議", jp: "メモを共有しました", subject: "I", answer: "shared", tail: "the notes.", full: "I shared the notes.", note: "共有した = shared。" },
  { id: "bm08", cat: "business", sub: "会議", jp: "内容をまとめました", subject: "I", answer: "summarized", tail: "the points.", full: "I summarized the points.", note: "まとめた = summarized。" },
  { id: "bm09", cat: "business", sub: "会議", jp: "次のステップを整理しました", subject: "I", answer: "organized", tail: "the next steps.", full: "I organized the next steps.", note: "整理した = organized。" },
  { id: "bm10", cat: "business", sub: "会議", jp: "画面を共有します", subject: "I", answer: "will", tail: "share my screen.", full: "I will share my screen.", note: "共有します = will share。" },
  { id: "bm11", cat: "business", sub: "会議", jp: "少し遅れて参加します", subject: "I", answer: "will", tail: "join a little late.", full: "I will join a little late.", note: "参加します = will join。" },
  { id: "bm12", cat: "business", sub: "会議", jp: "5分遅れます", subject: "I", answer: "will", tail: "be five minutes late.", full: "I will be five minutes late.", note: "遅れます = will be late。" },
  { id: "bm13", cat: "business", sub: "会議", jp: "すぐ戻ります", subject: "I", answer: "will", tail: "be right back.", full: "I will be right back.", note: "すぐ戻る = will be right back。" },
  { id: "bm14", cat: "business", sub: "会議", jp: "アジェンダを作りました", subject: "I", answer: "made", tail: "an agenda.", full: "I made an agenda.", note: "作った = made。" },
  { id: "bm15", cat: "business", sub: "会議", jp: "会議室を予約しました", subject: "I", answer: "booked", tail: "a meeting room.", full: "I booked a meeting room.", note: "予約した = booked。" },
  { id: "bm16", cat: "business", sub: "会議", jp: "発表をしました", subject: "I", answer: "gave", tail: "a presentation.", full: "I gave a presentation.", note: "発表した = gave a presentation。" },

  // ===== ビジネス: 確認・依頼 (business / confirm) =====
  { id: "bc01", cat: "business", sub: "確認", jp: "担当者を確認します", subject: "I", answer: "will", tail: "confirm who is in charge.", full: "I will confirm who is in charge.", note: "確認します = will confirm。" },
  { id: "bc02", cat: "business", sub: "確認", jp: "担当者に確認します", subject: "I", answer: "will", tail: "check with the person in charge.", full: "I will check with the person in charge.", note: "人に確認 = check with。" },
  { id: "bc03", cat: "business", sub: "確認", jp: "後で確認します", subject: "I", answer: "will", tail: "check it later.", full: "I will check it later.", note: "後でやる = will check。" },
  { id: "bc04", cat: "business", sub: "確認", jp: "社内で確認します", subject: "I", answer: "will", tail: "check internally.", full: "I will check internally.", note: "社内で確認 = check internally。" },
  { id: "bc05", cat: "business", sub: "確認", jp: "クライアントに確認します", subject: "I", answer: "will", tail: "check with the client.", full: "I will check with the client.", note: "相手に確認 = check with。" },
  { id: "bc06", cat: "business", sub: "確認", jp: "いったん確認します", subject: "I", answer: "will", tail: "check first.", full: "I will check first.", note: "いったん確認 = will check first。" },
  { id: "bc07", cat: "business", sub: "確認", jp: "少し確認が必要です", subject: "I", answer: "need", tail: "to check a few things.", full: "I need to check a few things.", note: "必要です = need to。" },
  { id: "bc08", cat: "business", sub: "確認", jp: "見積もりを確認する必要があります", subject: "I", answer: "need", tail: "to check the estimate.", full: "I need to check the estimate.", note: "〜する必要 = need to。" },
  { id: "bc09", cat: "business", sub: "確認", jp: "1点だけ確認したいです", subject: "I", answer: "want", tail: "to check one thing.", full: "I want to check one thing.", note: "確認したい = want to check。" },
  { id: "bc10", cat: "business", sub: "確認", jp: "前提を確認します", subject: "I", answer: "will", tail: "confirm the assumptions.", full: "I will confirm the assumptions.", note: "前提確認 = confirm assumptions。" },
  { id: "bc11", cat: "business", sub: "確認", jp: "事実を確認しました", subject: "I", answer: "confirmed", tail: "the facts.", full: "I confirmed the facts.", note: "確認した = confirmed。" },
  { id: "bc12", cat: "business", sub: "確認", jp: "もう一度確認しました", subject: "I", answer: "double-checked", tail: "it.", alts: ["double checked"], full: "I double-checked it.", note: "再確認した = double-checked。" },
  { id: "bc13", cat: "business", sub: "確認", jp: "状況を確認しました", subject: "I", answer: "checked", tail: "the status.", full: "I checked the status.", note: "確認した = checked。" },
  { id: "bc14", cat: "business", sub: "確認", jp: "詳細を確認します", subject: "I", answer: "will", tail: "check the details.", full: "I will check the details.", note: "確認します = will check。" },

  // ===== ビジネス: 修正・更新 (business / edit) =====
  { id: "bd01", cat: "business", sub: "修正", jp: "修正しました", subject: "I", answer: "fixed", tail: "it.", full: "I fixed it.", note: "直した = fixed。" },
  { id: "bd02", cat: "business", sub: "修正", jp: "一部を修正しました", subject: "I", answer: "updated", tail: "part of it.", full: "I updated part of it.", note: "更新・修正した = updated。" },
  { id: "bd03", cat: "business", sub: "修正", jp: "文言を変更しました", subject: "I", answer: "changed", tail: "the wording.", full: "I changed the wording.", note: "変えた = changed。" },
  { id: "bd04", cat: "business", sub: "修正", jp: "レイアウトを調整しました", subject: "I", answer: "adjusted", tail: "the layout.", full: "I adjusted the layout.", note: "調整した = adjusted。" },
  { id: "bd05", cat: "business", sub: "修正", jp: "色を変更しました", subject: "I", answer: "changed", tail: "the color.", full: "I changed the color.", note: "変更した = changed。" },
  { id: "bd06", cat: "business", sub: "修正", jp: "ボタンを追加しました", subject: "I", answer: "added", tail: "a button.", full: "I added a button.", note: "追加した = added。" },
  { id: "bd07", cat: "business", sub: "修正", jp: "不要な項目を削除しました", subject: "I", answer: "removed", tail: "the unnecessary item.", full: "I removed the unnecessary item.", note: "削除した = removed。" },
  { id: "bd08", cat: "business", sub: "修正", jp: "表を更新しました", subject: "I", answer: "updated", tail: "the table.", full: "I updated the table.", note: "更新した = updated。" },
  { id: "bd09", cat: "business", sub: "修正", jp: "誤字を直しました", subject: "I", answer: "fixed", tail: "the typo.", full: "I fixed the typo.", note: "直した = fixed。" },
  { id: "bd10", cat: "business", sub: "修正", jp: "資料を作り直しました", subject: "I", answer: "remade", tail: "the document.", full: "I remade the document.", note: "作り直した = remade。" },
  { id: "bd11", cat: "business", sub: "修正", jp: "あとで資料を更新します", subject: "I", answer: "will", tail: "update the document later.", full: "I will update the document later.", note: "更新します = will update。" },
  { id: "bd12", cat: "business", sub: "修正", jp: "順番を入れ替えました", subject: "I", answer: "changed", tail: "the order.", alts: ["reordered"], full: "I changed the order.", note: "入れ替えた = changed the order。" },
  { id: "bd13", cat: "business", sub: "修正", jp: "タイトルを変えました", subject: "I", answer: "changed", tail: "the title.", full: "I changed the title.", note: "変えた = changed。" },
  { id: "bd14", cat: "business", sub: "修正", jp: "前のバージョンに戻しました", subject: "I", answer: "reverted", tail: "to the previous version.", full: "I reverted to the previous version.", note: "戻した = reverted。" },

  // ===== ビジネス: 進捗・作業 (business / progress) =====
  { id: "bp01", cat: "business", sub: "進捗", jp: "作業を始めました", subject: "I", answer: "started", tail: "working on it.", full: "I started working on it.", note: "着手した = started working on it。" },
  { id: "bp02", cat: "business", sub: "進捗", jp: "作業を続けます", subject: "I", answer: "will", tail: "keep working on it.", full: "I will keep working on it.", note: "続けます = will keep working。" },
  { id: "bp03", cat: "business", sub: "進捗", jp: "作業を終えました", subject: "I", answer: "finished", tail: "working on it.", full: "I finished working on it.", note: "終えた = finished。" },
  { id: "bp04", cat: "business", sub: "進捗", jp: "まだ作業中です", subject: "I", answer: "am", tail: "still working on it.", full: "I am still working on it.", note: "まだ作業中 = am still working。" },
  { id: "bp05", cat: "business", sub: "進捗", jp: "少し詰まっています", subject: "I", answer: "am", tail: "a bit stuck.", full: "I am a bit stuck.", note: "詰まっている = am stuck。" },
  { id: "bp06", cat: "business", sub: "進捗", jp: "順調に進んでいます", subject: "I", answer: "am", tail: "making good progress.", full: "I am making good progress.", note: "順調 = making good progress。" },
  { id: "bp07", cat: "business", sub: "進捗", jp: "ほぼ終わりました", subject: "I", answer: "am", tail: "almost done.", full: "I am almost done.", note: "ほぼ終わり = am almost done。" },
  { id: "bp08", cat: "business", sub: "進捗", jp: "今日中に対応します", subject: "I", answer: "will", tail: "handle it by the end of today.", full: "I will handle it by the end of today.", note: "対応します = will handle。" },
  { id: "bp09", cat: "business", sub: "進捗", jp: "進捗を報告しました", subject: "I", answer: "reported", tail: "the progress.", full: "I reported the progress.", note: "報告した = reported。" },
  { id: "bp10", cat: "business", sub: "進捗", jp: "タスクを引き継ぎました", subject: "I", answer: "took", tail: "over the task.", full: "I took over the task.", note: "引き継いだ = took over。" },
  { id: "bp11", cat: "business", sub: "進捗", jp: "作業を分担しました", subject: "I", answer: "divided", tail: "the work.", full: "I divided the work.", note: "分担した = divided。" },
  { id: "bp12", cat: "business", sub: "進捗", jp: "少し時間が必要です", subject: "I", answer: "need", tail: "some time.", full: "I need some time.", note: "時間が必要 = need some time。" },

  // ===== ビジネス: 締切・予定 (business / deadline) =====
  { id: "bl01", cat: "business", sub: "締切", jp: "期限を確認しました", subject: "I", answer: "checked", tail: "the deadline.", full: "I checked the deadline.", note: "確認した = checked。" },
  { id: "bl02", cat: "business", sub: "締切", jp: "締切に間に合いました", subject: "I", answer: "met", tail: "the deadline.", full: "I met the deadline.", note: "間に合う = meet the deadline。" },
  { id: "bl03", cat: "business", sub: "締切", jp: "締切に間に合いませんでした", subject: "I", answer: "missed", tail: "the deadline.", full: "I missed the deadline.", note: "逃した = missed。" },
  { id: "bl04", cat: "business", sub: "締切", jp: "締切を延ばしてもらいました", subject: "I", answer: "got", tail: "an extension.", full: "I got an extension.", note: "延長してもらった = got an extension。" },
  { id: "bl05", cat: "business", sub: "締切", jp: "スケジュールを立てました", subject: "I", answer: "made", tail: "a schedule.", full: "I made a schedule.", note: "立てた = made。" },
  { id: "bl06", cat: "business", sub: "締切", jp: "予定を前倒ししました", subject: "I", answer: "moved", tail: "it up.", full: "I moved it up.", note: "前倒しした = moved up。" },
  { id: "bl07", cat: "business", sub: "締切", jp: "予定を後ろにずらしました", subject: "I", answer: "pushed", tail: "it back.", full: "I pushed it back.", note: "ずらした = pushed back。" },
  { id: "bl08", cat: "business", sub: "締切", jp: "リマインダーを設定しました", subject: "I", answer: "set", tail: "a reminder.", full: "I set a reminder.", note: "設定した = set。" },
  { id: "bl09", cat: "business", sub: "締切", jp: "優先度を上げました", subject: "I", answer: "raised", tail: "the priority.", full: "I raised the priority.", note: "上げた = raised。" },
  { id: "bl10", cat: "business", sub: "締切", jp: "優先度を下げました", subject: "I", answer: "lowered", tail: "the priority.", full: "I lowered the priority.", note: "下げた = lowered。" },

  // ===== ビジネス: レビュー・承認 (business / review) =====
  { id: "br01", cat: "business", sub: "レビュー", jp: "コメントを追加しました", subject: "I", answer: "added", tail: "a comment.", full: "I added a comment.", note: "追加した = added。" },
  { id: "br02", cat: "business", sub: "レビュー", jp: "コメントに返信しました", subject: "I", answer: "replied", tail: "to the comment.", full: "I replied to the comment.", note: "返信した = replied。" },
  { id: "br03", cat: "business", sub: "レビュー", jp: "承認しました", subject: "I", answer: "approved", tail: "it.", full: "I approved it.", note: "承認した = approved。" },
  { id: "br04", cat: "business", sub: "レビュー", jp: "まだ承認していません", subject: "I", answer: "haven't", alts: ["have not"], tail: "approved it yet.", full: "I haven't approved it yet.", note: "まだしていない = haven't ... yet。" },
  { id: "br05", cat: "business", sub: "レビュー", jp: "フィードバックを送りました", subject: "I", answer: "sent", tail: "some feedback.", full: "I sent some feedback.", note: "送った = sent。" },
  { id: "br06", cat: "business", sub: "レビュー", jp: "内容を見直しました", subject: "I", answer: "reviewed", tail: "it.", full: "I reviewed it.", note: "見直した = reviewed。" },
  { id: "br07", cat: "business", sub: "レビュー", jp: "変更を反映しました", subject: "I", answer: "applied", tail: "the changes.", full: "I applied the changes.", note: "反映した = applied。" },
  { id: "br08", cat: "business", sub: "レビュー", jp: "差し戻しました", subject: "I", answer: "sent", tail: "it back.", full: "I sent it back.", note: "差し戻した = sent back。" },
  { id: "br09", cat: "business", sub: "レビュー", jp: "結果を共有します", subject: "I", answer: "will", tail: "share the findings.", full: "I will share the findings.", note: "共有します = will share。" },
  { id: "br10", cat: "business", sub: "レビュー", jp: "確認結果をまとめます", subject: "I", answer: "will", tail: "summarize the findings.", full: "I will summarize the findings.", note: "まとめます = will summarize。" },

  // ===== ビジネス: 調査・問題対応 (business / investigate) =====
  { id: "bi01", cat: "business", sub: "調査", jp: "原因を調べました", subject: "I", answer: "looked", tail: "into the cause.", full: "I looked into the cause.", note: "調べる = look into。" },
  { id: "bi02", cat: "business", sub: "調査", jp: "問題を見つけました", subject: "I", answer: "found", tail: "the issue.", full: "I found the issue.", note: "見つけた = found。" },
  { id: "bi03", cat: "business", sub: "調査", jp: "原因が分かりました", subject: "I", answer: "found", tail: "the cause.", full: "I found the cause.", note: "分かった = found。" },
  { id: "bi04", cat: "business", sub: "調査", jp: "原因はまだ分かりません", subject: "I", answer: "don't", alts: ["do not"], tail: "know the cause yet.", full: "I don't know the cause yet.", note: "まだ分からない = don't know yet。" },
  { id: "bi05", cat: "business", sub: "調査", jp: "問題を再現しました", subject: "I", answer: "reproduced", tail: "the issue.", full: "I reproduced the issue.", note: "再現した = reproduced。" },
  { id: "bi06", cat: "business", sub: "調査", jp: "数字を確認しました", subject: "I", answer: "checked", tail: "the numbers.", full: "I checked the numbers.", note: "確認した = checked。" },
  { id: "bi07", cat: "business", sub: "調査", jp: "結果を比較しました", subject: "I", answer: "compared", tail: "the results.", full: "I compared the results.", note: "比較した = compared。" },
  { id: "bi08", cat: "business", sub: "調査", jp: "影響を確認しました", subject: "I", answer: "checked", tail: "the impact.", full: "I checked the impact.", note: "確認した = checked。" },
  { id: "bi09", cat: "business", sub: "調査", jp: "データを集めました", subject: "I", answer: "collected", tail: "the data.", full: "I collected the data.", note: "集めた = collected。" },
  { id: "bi10", cat: "business", sub: "調査", jp: "問題を解決しました", subject: "I", answer: "solved", tail: "the problem.", full: "I solved the problem.", note: "解決した = solved。" },
  { id: "bi11", cat: "business", sub: "調査", jp: "リスクを整理しました", subject: "I", answer: "organized", tail: "the risks.", full: "I organized the risks.", note: "整理した = organized。" },
  { id: "bi12", cat: "business", sub: "調査", jp: "対策を考えました", subject: "I", answer: "thought", tail: "of a solution.", full: "I thought of a solution.", note: "考えた = thought of。" },

  // ===== ビジネス: 提案・相談 (business / propose) =====
  { id: "bo01", cat: "business", sub: "相談", jp: "チームに共有します", subject: "I", answer: "will", tail: "share it with the team.", full: "I will share it with the team.", note: "共有します = will share。" },
  { id: "bo02", cat: "business", sub: "相談", jp: "チームに相談します", subject: "I", answer: "will", tail: "talk to the team.", full: "I will talk to the team.", note: "相談する = talk to。" },
  { id: "bo03", cat: "business", sub: "相談", jp: "案を3つ出します", subject: "I", answer: "will", tail: "provide three options.", full: "I will provide three options.", note: "案を出す = provide options。" },
  { id: "bo04", cat: "business", sub: "相談", jp: "最初の案を選びました", subject: "I", answer: "chose", tail: "the first option.", full: "I chose the first option.", note: "選んだ = chose。" },
  { id: "bo05", cat: "business", sub: "相談", jp: "その案に賛成です", subject: "I", answer: "agree", tail: "with that option.", full: "I agree with that option.", note: "賛成 = agree with。" },
  { id: "bo06", cat: "business", sub: "相談", jp: "少し懸念があります", subject: "I", answer: "have", tail: "some concerns.", full: "I have some concerns.", note: "懸念がある = have concerns。" },
  { id: "bo07", cat: "business", sub: "相談", jp: "いくつか質問があります", subject: "I", answer: "have", tail: "a few questions.", full: "I have a few questions.", note: "質問がある = have questions。" },
  { id: "bo08", cat: "business", sub: "相談", jp: "提案しました", subject: "I", answer: "suggested", tail: "an idea.", full: "I suggested an idea.", note: "提案した = suggested。" },
  { id: "bo09", cat: "business", sub: "相談", jp: "少し補足します", subject: "I", answer: "will", tail: "add a little context.", full: "I will add a little context.", note: "補足します = will add context。" },
  { id: "bo10", cat: "business", sub: "相談", jp: "意見を求めました", subject: "I", answer: "asked", tail: "for feedback.", full: "I asked for feedback.", note: "求めた = asked for。" },
  { id: "bo11", cat: "business", sub: "相談", jp: "条件を整理します", subject: "I", answer: "will", tail: "organize the conditions.", full: "I will organize the conditions.", note: "整理します = will organize。" },
  { id: "bo12", cat: "business", sub: "相談", jp: "範囲を絞りました", subject: "I", answer: "narrowed", tail: "the scope.", full: "I narrowed the scope.", note: "絞った = narrowed。" },
  { id: "bo13", cat: "business", sub: "相談", jp: "範囲を広げました", subject: "I", answer: "expanded", tail: "the scope.", full: "I expanded the scope.", note: "広げた = expanded。" },
  { id: "bo14", cat: "business", sub: "相談", jp: "要件を確認しました", subject: "I", answer: "confirmed", tail: "the requirements.", full: "I confirmed the requirements.", note: "確認した = confirmed。" },
  { id: "bo15", cat: "business", sub: "相談", jp: "サンプルを作りました", subject: "I", answer: "created", tail: "a sample.", full: "I created a sample.", note: "作成した = created。" },
  { id: "bo16", cat: "business", sub: "相談", jp: "動作を確認しました", subject: "I", answer: "tested", tail: "the behavior.", full: "I tested the behavior.", note: "動作確認 = tested。" },

  // ===== 追加分 =====
  // 日常: 移動
  { id: "c021", cat: "daily", sub: "移動", jp: "終バスに乗れた", subject: "I", answer: "caught", tail: "the last bus.", full: "I caught the last bus.", note: "間に合って乗った = caught。" },
  { id: "c022", cat: "daily", sub: "移動", jp: "切符を買った", subject: "I", answer: "bought", tail: "a ticket.", full: "I bought a ticket.", note: "買った = bought。" },
  { id: "c023", cat: "daily", sub: "移動", jp: "ICカードをチャージした", subject: "I", answer: "charged", tail: "my IC card.", full: "I charged my IC card.", note: "チャージした = charged。" },
  // 日常: 買い物
  { id: "s016", cat: "daily", sub: "買い物", jp: "お店に問い合わせた", subject: "I", answer: "contacted", tail: "the store.", full: "I contacted the store.", note: "問い合わせた = contacted。" },
  { id: "s017", cat: "daily", sub: "買い物", jp: "ネットで注文した", subject: "I", answer: "ordered", tail: "it online.", full: "I ordered it online.", note: "注文した = ordered。" },
  { id: "s018", cat: "daily", sub: "買い物", jp: "荷物を受け取った", subject: "I", answer: "received", tail: "the package.", full: "I received the package.", note: "受け取った = received。" },
  // 日常: 体調
  { id: "h016", cat: "daily", sub: "体調", jp: "深呼吸をした", subject: "I", answer: "took", tail: "a deep breath.", full: "I took a deep breath.", note: "深呼吸した = took a deep breath。" },
  { id: "h017", cat: "daily", sub: "体調", jp: "少し疲れていた", subject: "I", answer: "felt", tail: "a little tired.", full: "I felt a little tired.", note: "疲れていた = felt tired。" },
  // 日常: 家事
  { id: "ch15", cat: "daily", sub: "家事", jp: "アイロンをかけた", subject: "I", answer: "ironed", tail: "my shirt.", full: "I ironed my shirt.", note: "アイロンをかけた = ironed。" },
  { id: "ch16", cat: "daily", sub: "家事", jp: "ベランダを掃除した", subject: "I", answer: "cleaned", tail: "the balcony.", full: "I cleaned the balcony.", note: "掃除した = cleaned。" },
  // 日常: 飲食
  { id: "f013", cat: "daily", sub: "飲食", jp: "材料を切った", subject: "I", answer: "cut", tail: "the ingredients.", full: "I cut the ingredients.", note: "切った = cut（過去形も同じ）。" },
  { id: "f014", cat: "daily", sub: "飲食", jp: "テーブルを予約した", subject: "I", answer: "reserved", tail: "a table.", full: "I reserved a table.", note: "予約した = reserved。" },
  // 日常: 連絡
  { id: "n013", cat: "daily", sub: "連絡", jp: "メモを残した", subject: "I", answer: "left", tail: "a note.", full: "I left a note.", note: "残した = left。" },
  { id: "n014", cat: "daily", sub: "連絡", jp: "招待を受けた", subject: "I", answer: "accepted", tail: "the invitation.", full: "I accepted the invitation.", note: "受けた = accepted。" },
  // 日常: 天気
  { id: "w011", cat: "daily", sub: "天気", jp: "暖房をつけた", subject: "I", answer: "turned", tail: "on the heater.", full: "I turned on the heater.", note: "つけた = turned on。" },
  { id: "w012", cat: "daily", sub: "天気", jp: "カーテンを閉めた", subject: "I", answer: "closed", tail: "the curtains.", full: "I closed the curtains.", note: "閉めた = closed。" },
  // 日常: 家族
  { id: "fa11", cat: "daily", sub: "家族", jp: "子どもを寝かしつけた", subject: "I", answer: "put", tail: "my child to bed.", full: "I put my child to bed.", note: "寝かしつけた = put ... to bed。" },
  { id: "fa12", cat: "daily", sub: "家族", jp: "家族と過ごした", subject: "I", answer: "spent", tail: "time with my family.", full: "I spent time with my family.", note: "過ごした = spent time。" },
  // 日常: 余暇
  { id: "l013", cat: "daily", sub: "余暇", jp: "コンサートに行った", subject: "I", answer: "went", tail: "to a concert.", full: "I went to a concert.", note: "行った = went to。" },
  { id: "l014", cat: "daily", sub: "余暇", jp: "絵を描いた", subject: "I", answer: "drew", tail: "a picture.", full: "I drew a picture.", note: "描いた = drew。" },
  // 日常: トラブル
  { id: "t011", cat: "daily", sub: "トラブル", jp: "予約をすっぽかした", subject: "I", answer: "missed", tail: "my appointment.", full: "I missed my appointment.", note: "すっぽかした = missed。" },
  { id: "t012", cat: "daily", sub: "トラブル", jp: "名前を間違えてしまった", subject: "I", answer: "got", tail: "the name wrong.", full: "I got the name wrong.", note: "間違えた = got ... wrong。" },

  // ビジネス: メール
  { id: "be13", cat: "business", sub: "メール", jp: "宛先を間違えました", subject: "I", answer: "sent", tail: "it to the wrong person.", full: "I sent it to the wrong person.", note: "間違えて送った = sent to the wrong person。" },
  { id: "be14", cat: "business", sub: "メール", jp: "お礼のメールを送りました", subject: "I", answer: "sent", tail: "a thank-you email.", full: "I sent a thank-you email.", note: "送った = sent。" },
  // ビジネス: 会議
  { id: "bm17", cat: "business", sub: "会議", jp: "日程を調整しました", subject: "I", answer: "arranged", tail: "the schedule.", full: "I arranged the schedule.", note: "調整した = arranged。" },
  { id: "bm18", cat: "business", sub: "会議", jp: "会議に間に合いました", subject: "I", answer: "made", tail: "it to the meeting.", full: "I made it to the meeting.", note: "間に合った = made it to。" },
  // ビジネス: 確認
  { id: "bc15", cat: "business", sub: "確認", jp: "在庫を確認します", subject: "I", answer: "will", tail: "check the stock.", full: "I will check the stock.", note: "確認します = will check。" },
  { id: "bc16", cat: "business", sub: "確認", jp: "金額を確認しました", subject: "I", answer: "checked", tail: "the amount.", full: "I checked the amount.", note: "確認した = checked。" },
  // ビジネス: 修正
  { id: "bd15", cat: "business", sub: "修正", jp: "リンクを直しました", subject: "I", answer: "fixed", tail: "the link.", full: "I fixed the link.", note: "直した = fixed。" },
  { id: "bd16", cat: "business", sub: "修正", jp: "説明を加えました", subject: "I", answer: "added", tail: "an explanation.", full: "I added an explanation.", note: "加えた = added。" },
  // ビジネス: 進捗
  { id: "bp13", cat: "business", sub: "進捗", jp: "明日から取りかかります", subject: "I", answer: "will", tail: "start tomorrow.", full: "I will start tomorrow.", note: "取りかかります = will start。" },
  { id: "bp14", cat: "business", sub: "進捗", jp: "予定通り進めます", subject: "I", answer: "will", tail: "proceed as planned.", full: "I will proceed as planned.", note: "進めます = will proceed。" },
  // ビジネス: 締切
  { id: "bl11", cat: "business", sub: "締切", jp: "余裕を持って終わらせました", subject: "I", answer: "finished", tail: "ahead of schedule.", full: "I finished ahead of schedule.", note: "前倒しで終えた = finished ahead of schedule。" },
  { id: "bl12", cat: "business", sub: "締切", jp: "締切を伝えました", subject: "I", answer: "shared", tail: "the deadline.", full: "I shared the deadline.", note: "伝えた = shared。" },
  // ビジネス: レビュー
  { id: "br11", cat: "business", sub: "レビュー", jp: "修正をお願いしました", subject: "I", answer: "asked", tail: "for some changes.", full: "I asked for some changes.", note: "お願いした = asked for。" },
  { id: "br12", cat: "business", sub: "レビュー", jp: "問題ないと伝えました", subject: "I", answer: "said", tail: "it looked good.", full: "I said it looked good.", note: "伝えた = said。" },
  // ビジネス: 調査
  { id: "bi13", cat: "business", sub: "調査", jp: "ログを確認しました", subject: "I", answer: "checked", tail: "the logs.", full: "I checked the logs.", note: "確認した = checked。" },
  { id: "bi14", cat: "business", sub: "調査", jp: "原因を特定しました", subject: "I", answer: "identified", tail: "the cause.", full: "I identified the cause.", note: "特定した = identified。" },
  // ビジネス: 相談
  { id: "bo17", cat: "business", sub: "相談", jp: "上司に確認します", subject: "I", answer: "will", tail: "check with my manager.", full: "I will check with my manager.", note: "確認します = check with。" },
  { id: "bo18", cat: "business", sub: "相談", jp: "アドバイスをもらいました", subject: "I", answer: "got", tail: "some advice.", full: "I got some advice.", note: "もらった = got。" },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { QUESTIONS };
}
